#!/bin/sh
if [ $# -eq 0 ] ; then
    echo 'Usage: get_secret secret_key'
    exit 0
fi

cat /config/secrets.yaml \
| grep ^$1: \
| sed -e 's/\s*:\s*/:/g' \
| sed -e 's/\s*,\s*/,/g' \
| sed -e 's/"//g' \
| sed -e "s/'//g" \
| sed -e 's/ *$//' \
| sed -e 's/ /_/g' \
| grep -Eo ':.*' \
| sed -e 's/://'

#sed -e 's/\s*:\s*/:/g' -> remove spaces before and after :
#sed -e 's/\s*,\s*/,/g' -> remove spaces before and after ,
#sed -e 's/"//g' -> remove all "
#sed -e "s/'//g" -> remove all '
#sed -e 's/ *$//' -> remove spaces at the end of line
#sed -e 's/ /_/g' -> replace spaces with _
#sed -e 's/://' -> remove :
