#!/bin/sh
if [ $# -eq 0 ] ; then
    echo 'Usage: get_secret secret_key'
    exit 0
fi
cat /config/secrets.yaml | grep ^$1: | sed -e 's/ //' | sed -e 's/ *$//' | sed -e 's/ /_/g' | grep -Eo ':.*' | sed 's/://'
