#########################################################
#                                                       #
#                       SCRIPT                          #
#                                                       #
#########################################################
shell_command:
  smarther_update: __update_cmd__

script:
  update_from_smarther_github_repo:
    alias: Update smarther integration from GitHub repository
    sequence:
      - service: shell_command.smarther_update

#########################################################
#                                                       #
#                        SENSOR                         #
#                                                       #
#########################################################
sensor:
  - platform: command_line
    name: "Smarther current release"
    command: cat /config/smarther/.smarther_version
    scan_interval: 10800
    value_template: "{{ value_json.tag_name }}"
    json_attributes:
      - "html_url"
      - "name"
      - "draft"
      - "prerelease"
      - "published_at"
      - "body"

  - platform: command_line
    name: "Smarther latest release"
    command: __latest_release_cmd__
    scan_interval: 3600
    value_template: "{{ value_json.tag_name }}"
    json_attributes:
      - "html_url"
      - "name"
      - "draft"
      - "prerelease"
      - "published_at"
      - "body"

#########################################################
#                                                       #
#                    BINARY SENSOR                      #
#                                                       #
#########################################################
binary_sensor:
  - platform: template
    sensors:
      smarther_updater:
        friendly_name: "Smarther updater"
        value_template: "{{ states('sensor.smarther_current_release') < states('sensor.smarther_latest_release') }}"
        device_class: moving
        attribute_templates:
          current_version: "{{ states('sensor.smarther_current_release') }}"
          latest_version: "{{ states('sensor.smarther_latest_release') }}"
