name: Make Release

on:
  push:
    branches:
      - master
  
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Version
        shell: bash
        id: version
        run: |
          today="$(date --utc '+%Y-%m-%d')"
          midnight_timestamp="$(date --utc +%s --date=$today)"
          #calver_date="$(date --utc --date=$today '+%Y.%m.%d')"
          calver_date="$(date --utc --date=$today '+%y.%j')"
          commit_count="$(git rev-list --count --since=$midnight_timestamp HEAD)"
          commit_count="$(printf "%02d" ${commit_count})"
          version="v${calver_date}.${commit_count}"
          echo "::set-output name=version::$version"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
